# Generated by Django 4.2.7 on 2023-11-18 17:40

import apps.testimonials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(validators=[apps.testimonials.models.validate_rating])),
                ('content', models.TextField()),
            ],
        ),
    ]
