# Generated by Django 4.2.7 on 2023-11-30 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_account', 'View account')]), blank=True, default=list, null=True, size=None, verbose_name='permissions'),
        ),
    ]
