# Generated by Django 4.2.7 on 2023-11-21 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('namespace', models.CharField(db_index=True, default='default', max_length=250)),
                ('event_type', models.CharField(db_index=True, max_length=250)),
                ('data', models.JSONField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_timelines', to='contenttypes.contenttype')),
                ('data_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_timelines', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', '-created'], name='timeline_ti_namespa_89bca1_idx'), models.Index(fields=['content_type', 'object_id', '-created'], name='timeline_ti_content_1af26f_idx')],
            },
        ),
    ]
