version: '3'
services:
    api:
        build:
            context: ./docker/api
            dockerfile: Dockerfile
            args:
                APP_ENV: '${APP_ENV}'
                HOST_GID: '${HOST_API_UID:-1001}'
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${API_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${API_HTTP_PORT:-8000}'
            HOST_API_UID: '${HOST_API_UID:-1001}'
            APP_ENV: '${APP_ENV}'
            APP_SCHEDULE: '${APP_SCHEDULE:-false}'
        volumes:
            - './api:/var/www/html'
        networks:
            - realjournals
            - nginx-proxy
        depends_on:
            - postgres
            - rabbitmq
            - redis

    redis:
        build:
            context: ./docker/redis
            dockerfile: Dockerfile
            args:
                REDIS_VERSION: '${REDIS_VERSION:-6}'
        restart: unless-stopped
        volumes:
            - 'realjournals-redis:/data'
        networks:
            - realjournals
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    rabbitmq:
        image: "rabbitmq:3-management"
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
        networks:
            - realjournals

    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
        networks:
            - realjournals

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${API_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${NGINX_HTTP_PORT:-"80"}'
            VIRTUAL_HTTPS_PORT: '${NGINX_HTTPS_PORT:-"443"}'
            API_DOMAIN: '${API_DOMAIN:-api.realjournals.com}'
            NGINX_DEFAULT_API_CONFIG: '${NGINX_DEFAULT_API_CONFIG}'
        ports:
            - '${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}'
            - '${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}'
        volumes:
            - '.:/var/www/html'
            - '${HOME}/www/certbot:/var/www/certbot'
            - '${HOME}/lib/letsencrypt:/var/lib/letsencrypt'
            - '${HOME}/letsencrypt:/etc/letsencrypt'
        networks:
            - nginx-proxy
        depends_on:
            - api
        healthcheck:
            test: ["CMD-SHELL", "service nginx status || exit 1"]

networks:
    nginx-proxy:
        external: true
    realjournals:
        driver: bridge
volumes:
    realjournals-redis:
        driver: local
