# Generated by Django 4.2.7 on 2023-11-18 17:40

import apps.history.choices
import apps.history.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.CharField(default=apps.history.models._generate_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('user', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.SmallIntegerField(choices=[(apps.history.choices.HistoryType['change'], 'Change'), (apps.history.choices.HistoryType['create'], 'Create'), (apps.history.choices.HistoryType['delete'], 'Delete')])),
                ('key', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('diff', models.JSONField(blank=True, default=None, null=True)),
                ('values_diff_cache', models.JSONField(blank=True, default=None, null=True)),
                ('snapshot', models.JSONField(blank=True, default=None, null=True)),
                ('values', models.JSONField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True)),
                ('comment_html', models.TextField(blank=True)),
                ('delete_comment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('delete_comment_user', models.JSONField(blank=True, default=None, null=True)),
                ('comment_versions', models.JSONField(blank=True, default=None, null=True)),
                ('edit_comment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
