# Generated by Django 4.2.7 on 2023-11-18 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='How did you feel during this trade?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='accounts.account', verbose_name='account')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_journals', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
                'ordering': ['account', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalCustomAttributesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes_values', models.JSONField(default=dict, verbose_name='values')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_values', to='journals.journal', verbose_name='journal')),
            ],
            options={
                'verbose_name': 'journal custom attributes values',
                'verbose_name_plural': 'journal custom attributes values',
                'ordering': ['id'],
                'abstract': False,
                'index_together': {('journal',)},
            },
        ),
        migrations.CreateModel(
            name='JournalCustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-Line Text'), ('richtext', 'Rich text'), ('date', 'Date'), ('url', 'Url'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number')], default='text', max_length=16, verbose_name='type')),
                ('order', models.BigIntegerField(verbose_name='order')),
                ('extra', models.JSONField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'journal custom attribute',
                'verbose_name_plural': 'journal custom attributes',
                'ordering': ['account', 'order', 'name'],
                'abstract': False,
                'unique_together': {('account', 'name')},
            },
        ),
    ]
