# Generated by Django 4.2.7 on 2023-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'United States dollar'), ('EUR', 'European Euro'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar'), ('CHF', 'Swiss franc'), ('CNY', 'Chinese/Yuan renminbi'), ('SEK', 'Swedish krona'), ('NZD', 'New Zealand dollar'), ('SGD', 'Singapore dollar'), ('HKD', 'Hong Kong dollar'), ('KRW', 'South Korean won'), ('INR', 'Indian rupee'), ('BRL', 'Brazilian real'), ('MXN', 'Mexican peso'), ('ZAR', 'South African rand'), ('AED', 'UAE dirham'), ('TRY', 'Turkish new lira'), ('RUB', 'Russian ruble'), ('NOK', 'Norwegian krone'), ('DKK', 'Danish krone')], default='USD', max_length=3, null=True),
        ),
    ]
