# Generated by Django 4.2.7 on 2023-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='assets',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='commission_blocked',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency_digits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='fifo_close',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='leverage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='liabilities',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit_orders',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_free',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_initial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_maintenance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_mode',
            field=models.IntegerField(choices=[(0, 'Retail Netting'), (1, 'Exchange'), (2, 'Retail Hedging')], default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_so_call',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_so_mode',
            field=models.IntegerField(choices=[(0, 'Percent'), (1, 'Money')], default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='margin_so_so',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='trade_mode',
            field=models.IntegerField(choices=[(0, 'Demo'), (1, 'Contest'), (2, 'Real')], default=2),
        ),
    ]
