# Generated by Django 4.2.7 on 2023-11-30 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='commission_blocked',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency_digits',
        ),
        migrations.RemoveField(
            model_name='account',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fifo_close',
        ),
        migrations.RemoveField(
            model_name='account',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='account',
            name='liabilities',
        ),
        migrations.RemoveField(
            model_name='account',
            name='limit_orders',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_free',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_initial',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_maintenance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_mode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_so_call',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_so_mode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_so_so',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='server',
        ),
        migrations.RemoveField(
            model_name='account',
            name='trade_allowed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='trade_expert',
        ),
        migrations.RemoveField(
            model_name='account',
            name='trade_mode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_account', 'View account')], default=[]), size=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocked_code',
            field=models.CharField(blank=True, choices=[('blocked-by-nonpayment', 'This account is blocked due to payment failure'), ('blocked-by-staff', 'This account is blocked by admin staff'), ('blocked-by-owner-leaving', 'This account is blocked because the owner left'), ('blocked-by-deleting', "This account is blocked while it's deleted")], default=None, max_length=255, null=True, verbose_name='blocked code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_account', 'View account')], default=[]), size=None),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_account', 'View account')]), blank=True, default=list, null=True, size=None, verbose_name='permissions'),
        ),
    ]
