# Generated by Django 4.2.8 on 2023-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_amount_account_assets_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
