# Generated by Django 4.2.8 on 2023-12-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_anon_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point',
        ),
    ]
