# Generated by Django 4.2.8 on 2023-12-18 01:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_amount_remove_account_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 1, 51, 32, 502480), verbose_name='start date'),
        ),
    ]
