# Generated by Django 4.2.8 on 2023-12-19 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_end_date_account_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 19, 24, 55, 557085), verbose_name='start date'),
        ),
        migrations.CreateModel(
            name='TradeDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField()),
                ('order', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell'), (2, 'Balance'), (3, 'Credit'), (4, 'Charge'), (5, 'Correction'), (6, 'Bonus'), (7, 'Commission'), (8, 'Commission Daily'), (9, 'Commission Monthly'), (10, 'Commission Agent Daily'), (11, 'Commission Agent Monthly'), (12, 'Interest'), (13, 'Buy Canceled'), (14, 'Sell Canceled'), (15, 'Deal Dividend'), (16, 'Deal Dividend Franked'), (17, 'Deal Tax')])),
                ('entry', models.IntegerField(choices=[(0, 'In'), (1, 'Out'), (2, 'Inout'), (3, 'Out By')])),
                ('magic', models.IntegerField()),
                ('position_id', models.IntegerField()),
                ('reason', models.IntegerField(choices=[(1, 'The deal was executed as a result of activation of an order placed from a desktop terminal'), (2, 'The deal was executed as a result of activation of an order placed from a mobile application'), (3, 'The deal was executed as a result of activation of an order placed from the web platform'), (4, 'The deal was executed as a result of activation of an order placed from an MQL5 program, i.e. an Expert Advisor or a script'), (5, 'The deal was executed as a result of Stop Loss activation'), (6, 'The deal was executed as a result of Take Profit activation'), (7, 'The deal was executed as a result of the Stop Out event'), (8, 'The deal was executed due to a rollover'), (9, 'The deal was executed after charging the variation margin'), (10, 'The deal was executed after the split (price reduction) of an instrument, which had an open position during split announcement')])),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('commission', models.FloatField()),
                ('swap', models.FloatField()),
                ('profit', models.FloatField()),
                ('fee', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('symbol', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_deal', to='accounts.account')),
            ],
        ),
    ]
