# Generated by Django 4.2.8 on 2023-12-31 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_start_date_tradedeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='end_date',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 23, 9, 41, 211716), verbose_name='start date'),
        ),
        migrations.DeleteModel(
            name='TradeDeal',
        ),
    ]
