# Generated by Django 4.2.8 on 2023-12-31 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_end_date_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 23, 23, 15, 743615), verbose_name='start date'),
        ),
    ]
