# Generated by Django 4.2.8 on 2024-01-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 16, 14, 54, 974976), verbose_name='start date'),
        ),
    ]
