# Generated by Django 4.2.8 on 2024-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='instructions'),
        ),
        migrations.AddField(
            model_name='broker',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
