# Generated by Django 4.2.8 on 2024-01-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_broker_auto_instructions_broker_auto_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_type',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional')], default='UTC', max_length=63),
        ),
        migrations.AddField(
            model_name='account',
            name='is_monthly_billing',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is Billed Monthly'),
        ),
    ]
