# Generated by Django 4.2.8 on 2024-01-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_billing_type_account_is_monthly_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last end date'),
        ),
    ]
