# Generated by Django 4.2.9 on 2024-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_account_last_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_end_date',
        ),
        migrations.AddField(
            model_name='account',
            name='last_deal_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last deal end date'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_order_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last deal end date'),
        ),
    ]
