# Generated by Django 4.2.7 on 2023-11-21 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5)),
                ('direction', models.CharField(choices=[('rtl', 'Right to Left'), ('ltr', 'Left to Right')], default='ltr', max_length=3)),
                ('color', models.CharField(choices=[('default', 'Default'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('orange', 'Orange'), ('red', 'Red')], default='default', max_length=7)),
                ('stretch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalPageModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('terminal.dashboard', 'Terminal Dashboard'), ('terminal.journal', 'Terminal Journal')], default='terminal.dashboard', max_length=255)),
                ('module', models.CharField(choices=[('net_profit_loss', 'Net Profit and Loss'), ('trade_win_percentage', 'Trade Win Percentage'), ('profit_factor', 'Profit Factor'), ('day_win_percentage', 'Day Win Percentage'), ('average_win_loss_trade', 'Average Win/Loss Trade'), ('daily_net_cummulative_profit_loss', 'Daily Net Cummulative Profit & Loss'), ('net_daily_profit_loss', 'Net Daily Profit & Loss'), ('recent_timeline', 'Recent Timeline'), ('recent_trades', 'Recent Trades'), ('calendar', 'Calendar'), ('account_balance', 'Account Balance'), ('account_balance_chart', 'Account Balance Chart')], default='net_profit_loss', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_pages', to='accounts.account')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('account', 'page', 'module')},
            },
        ),
        migrations.CreateModel(
            name='AdminPageModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('admin.dashboard', 'Terminal Dashboard')], default='admin.dashboard', max_length=255)),
                ('module', models.CharField(choices=[('latest_users', 'Latest Users'), ('registration_chart', 'Registration Chart'), ('system_status', 'System Status'), ('earning_summary', 'Earning Summary')], default='latest_users', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_admin_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('user', 'page', 'module')},
            },
        ),
        migrations.CreateModel(
            name='TerminalDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakpoint', models.CharField(choices=[('md', 'md'), ('sm', 'sm'), ('xs', 'xs'), ('lg', 'lg')], max_length=255)),
                ('w', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('h', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('moved', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('isResizable', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='settings.terminalpagemodule')),
            ],
            options={
                'unique_together': {('module', 'breakpoint', 'w', 'h', 'x', 'y', 'moved', 'static', 'isResizable')},
            },
        ),
        migrations.CreateModel(
            name='AdminDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakpoint', models.CharField(choices=[('md', 'md'), ('sm', 'sm'), ('xs', 'xs'), ('lg', 'lg')], max_length=255)),
                ('w', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('h', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('moved', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('isResizable', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='settings.adminpagemodule')),
            ],
            options={
                'unique_together': {('module', 'breakpoint')},
            },
        ),
    ]
