# Generated by Django 4.2.8 on 2023-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_terminalpagemodule_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='layout',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='vertical', max_length=15),
        ),
    ]
