# Generated by Django 4.2.9 on 2024-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_terminalpagemodule_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalpagemodule',
            name='module',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('total_trades', 'Total Trades'), ('winners', 'Winners'), ('lossers', 'Lossers'), ('trade_allocation', 'Trade Allocation'), ('invite_member_card', 'Invite Member'), ('net_profit_loss', 'Net Profit and Loss'), ('trade_win_percentage', 'Trade Win Percentage'), ('profit_factor', 'Profit Factor'), ('day_win_percentage', 'Day Win Percentage'), ('average_win_loss_trade', 'Average Win/Loss Trade'), ('daily_net_cummulative_profit_loss', 'Daily Net Cummulative Profit & Loss'), ('net_daily_profit_loss', 'Net Daily Profit & Loss'), ('recent_timeline', 'Recent Timeline'), ('recent_trades', 'Recent Trades'), ('calendar', 'Calendar'), ('account_balance', 'Account Balance'), ('account_balance_chart', 'Account Balance Chart')], default='net_profit_loss', max_length=255),
        ),
    ]
